### ISSUE TITLE
No google login UI after clicking the 'login' button from historymap menu

### ISSUE THREAD

**Issue by kaimdx** [Vis4Sense/HistoryMap#113]
This could be related to the permission that Reday has to set in his google developer console for each new machine because the extension is not registered in chrome app store.

**Comment by RedayY** [comment]
This is happening because the URL from the Client where the Login appears mismatches with the URL left in the Google+ API 0Auth credidentials page. 

For users that have this Issue : 
- Please run: redirectURI in the console of Background.html and comment results below.

What I have done for now: 
- I switched the ClientID in Manifest.JSON and login.JS which I have setup from a new Account
- Account Details shared with Kai, he has access to change Settings

What I require:
- I need users that experience this Issue or want to use the Login to run "redirectURI" in the console of Background.HTML and post results here.

Why this is happening:
- Moved Folder structure where Background.html is located 
- Extensions Client ID's have been updated by google
- Random reason I have not determined yet

Will this happen when the Extension is on the web store ?
- No, since right now were using a workaround where Sensemap is not hosted on the Webstore.

**Comment by kaimdx** [comment]
Just tried again and still have the same error message.

**Comment by RedayY** [comment]
I just came home from work, working on this now

**Comment by kaimdx** [comment]
I have created a new 'historymap' extension in the chrome web store: https://chrome.google.com/webstore/detail/historymap/jjgdemkolpjjdkgmfgolldlnoghhodlj
I tried to add the redirect uri with the new extension ID in the api console, but still have the same error: https://lajblbdkejaddpihfeeihnicfkmiojem.chromiumapp.org/src/background/backgroud.html

**Comment by RedayY** [comment]
What account did you use for the extension ? can you give me access so I can try setting up Oauth credentials ?

**Comment by RedayY** [comment]
I am working on this right now

**Comment by RedayY** [comment]
I updated Hello.js and I also fixed the issue with the login.

For anyone else reading this and working on the login heres a handy wiki page I made :) 

https://github.com/Vis4Sense/HistoryMap/wiki/SenseMap-Login-on-a-Local-Environment

I also made a video tutorial https://www.youtube.com/watch?v=CU4TIDmKJgk&feature=youtu.be
