### ISSUE TITLE
All the nodes from a loaded session disappear after opening a new tab

### ISSUE THREAD

**Issue by kaidatavis** [Vis4Sense/HistoryMap#124]
It seems the nodes loaded from a session is not added to the `historyMap.model.nodes`.

![historymap-load-error](https://user-images.githubusercontent.com/1853740/42568033-9c1958c0-8503-11e8-949e-8bd0898f360f.gif)

**Comment by kaimdx** [comment]
@RedayY my understanding may be the same as yours: I think the issue is in 'laodSelectedSession' function the `database.js` (copied below). It clears out `nodes` array but doesn't populate it with saved data, so the historyMap becomes empty when it redraws. 

Instead, the saved data is used to populate `hsiotryMap.model.tree`, which is used to create the graphical representation in the historyMap window (so the display is correct immediately after a session is loaded). However, `historyMap.model.tree` is regenerated from `nodes` array every time historyMap refreshes, therefore historyMap will lose the nodes from saved data if they are not added to `nodes` when loading. 

I think the solution is to save the `nodes` array, instead of `historyMap.model.tree`, to the database.  When loading, the `nodes` array will be replaced with the saved session, and the `historyMap.model.tree` can be re-created using the updated `nodes` array. 

```js
//Function for loading
historyMap.database.sessions.loadSelectedSession = function (i) {

    //Clear Previous Values
    nodes.length = 0;
    SessionName = "";

    //set new values
    tempTree = CircularJSON.parse(i.nodes);
    historyMap.model.tree = tempTree;

    //reload history map
    historyMapView.width(window.innerWidth).height(window.innerHeight);
    d3.select('.sm-history-map-container').datum(historyMap.model.tree).call(historyMapView);

    //Set Values to Historymap from Session of Choice for save and load
    SessionName = i.name;
    DBSessionPointer = i._id;
};
```

**Comment by RedayY** [comment]
Ha I remember saying that back then but we went instead with the tree. I think the issue was with saving nodes indiviudally and getting the JSON circular reference error. But we fixed that thanks to a library. Ill see if I can populate both Nodes and tree at the same time when loading.
